### ISSUE TITLE
[Feature Request] apprepo.de integration ? 

### ISSUE THREAD

**Issue by SamDc73** [srevinsaju/zap#75]
apprepo.de have a large database of appimages, it will be nice if i can search and install apps from there without leaving zap .

**Comment by srevinsaju** [comment]
Although the apprepo.de has a lot of appimages, we still do not know how the binaries are built, and if the build scripts are open source. Since there is a possibility of introducing vulnerabilties, we currently do not plan to add apprepo.de support directly. However, you can install the AppImages from apprepo.de by URL, so that the user takes all responsibility of trusting the AppImage downloaded from apprepo.de.
